# Generated by Django 4.2.27 on 2026-03-31 22:27

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0075_interface_duplex_interface_speed_and_more'),
        ('extras', '0125_jobresult_date_started'),
        ('ipam', '0053_alter_vrfdeviceassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', nautobot.core.models.fields.AutoSlugField(blank=True, max_length=255, populate_from='name', unique=True)),
                ('default_admin_distance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RoutingTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=128)),
                ('slug', nautobot.core.models.fields.AutoSlugField(blank=True, max_length=255, populate_from='name', unique=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_tables', to='dcim.device')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('vrf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_tables', to='ipam.vrf')),
            ],
            options={
                'ordering': ('device__name', 'vrf__name'),
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RoutingProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=128)),
                ('slug', nautobot.core.models.fields.AutoSlugField(blank=True, max_length=255, populate_from='name', unique=True)),
                ('admin_distance_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('protocol_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocols', to='nautobot_routing_tables.protocoltype')),
                ('routing_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='nautobot_routing_tables.routingtable')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('routing_table__device__name', 'routing_table__vrf__name', 'name'),
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('next_hop_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metric', models.PositiveIntegerField(blank=True, null=True)),
                ('admin_distance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_managed', models.BooleanField(default=False)),
                ('next_hop_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_as_next_hop', to='dcim.interface')),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='ipam.prefix')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='nautobot_routing_tables.routingprotocol')),
                ('routing_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='nautobot_routing_tables.routingtable')),
                ('source_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_as_source', to='dcim.interface')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('routing_table__device__name', 'routing_table__vrf__name', 'prefix__prefix_length', 'prefix__network'),
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='routingtable',
            constraint=models.UniqueConstraint(fields=('device', 'vrf'), name='unique_routing_table_per_device_vrf'),
        ),
        migrations.AddConstraint(
            model_name='routingtable',
            constraint=models.UniqueConstraint(condition=models.Q(('vrf__isnull', True)), fields=('device',), name='unique_global_routing_table_per_device'),
        ),
        migrations.AddConstraint(
            model_name='routingprotocol',
            constraint=models.UniqueConstraint(fields=('routing_table', 'slug'), name='unique_protocol_per_table_slug'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('routing_table', 'prefix', 'protocol', 'next_hop_ip', 'next_hop_interface'), name='unique_route_semantics_per_table'),
        ),
    ]
